const users = [
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    name: "John Doe",
    email: "johndoe@example.com",
    password: "password123",
    role: "admin",
    image_url: "",
    socials: {
      facebook: "https://www.facebook.com/johndoe",
      twitter: "https://www.twitter.com/johndoe",
      linkedIn: "https://www.linkedin.com/in/johndoe",
    },
  },
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    name: "Jane Smith",
    email: "janesmith@example.com",
    password: "pass123",
    role: "user",
    image_url: "",
    socials: {
      facebook: "",
      twitter: "https://www.twitter.com/janesmith",
      linkedIn: "https://www.linkedin.com/in/janesmith",
    },
  },
  {
    id: '126eed9c-c90c-4ef6-a4a8-fcf7408d3c66',
    name: "Bob Johnson",
    email: "bob@example.com",
    password: "bobspassword",
    role: "user",
    image_url: "",
    socials: {
      facebook: "https://www.facebook.com/bobjohnson",
      twitter: "",
      linkedIn: "",
    },
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    name: "Alice Brown",
    email: "alice@example.com",
    password: "qwerty",
    role: "user",
    image_url: "",
    socials: {
      facebook: "",
      twitter: "",
      linkedIn: "",
    },
  },
  {
    id: '13D07535-C59E-4157-A011-F8D2EF4E0CBB',
    name: "Michael Lee",
    email: "michael@example.com",
    password: "password1",
    role: "user",
    image_url: "",
    socials: {
      facebook: "https://www.facebook.com/michaellee",
      twitter: "https://www.twitter.com/michaellee",
      linkedIn: "",
    },
  },
];

const posts = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    image_url: "",
    title: "Tech Bootcamp",
    description: "Something I want to say. Something I want to say. Something I want to say. Something I want to say.",
    author: users[0].name,
    likes: 3,
    status: "private",
    date: '2022-10-29',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    image_url: "",
    title: "Web Development Trends",
    description: "Exploring the latest trends in web development. Stay updated!",
    author: users[1].name,
    likes: 7,
    status: "public",
    date: '2022-11-15',
  },
  {
    id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',
    image_url: "",
    title: "Artificial Intelligence in Healthcare",
    description: "How AI is revolutionizing the healthcare industry. Discover the advancements.",
    author: users[2].name,
    likes: 12,
    status: "public",
    date: '2022-12-02',
  },
  {
    id: '50ca3e18-62cd-11ee-8c99-0242ac120002',
    image_url: "",
    title: "Productivity Tips for Remote Work",
    description: "Maximize your productivity while working from home. Learn effective strategies.",
    author: users[3].name,
    likes: 5,
    status: "public",
    date: '2023-01-10',
  },
  {
    id: '3958dc9e-787f-4377-85e9-fec4b6a6442a',
    image_url: "",
    title: "Beginner's Guide to Python Programming",
    description: "A comprehensive guide for beginners to learn Python programming step by step.",
    author: users[4].name,
    likes: 9,
    status: "public",
    date: '2023-02-18',
  },
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    image_url: "",
    title: "The Future of Blockchain Technology",
    description: "Exploring the potential applications and impact of blockchain technology in various industries.",
    author: users[0].name,
    likes: 15,
    status: "public",
    date: '2023-03-25',
  },
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    image_url: "",
    title: "Introduction to Data Science",
    description: "Learn the basics of data science and its importance in today's data-driven world.",
    author: users[1].name,
    likes: 6,
    status: "public",
    date: '2023-04-10',
  },
  {
    id: '126eed9c-c90c-4ef6-a4a8-fcf7408d3c66',
    image_url: "",
    title: "Mastering JavaScript Frameworks",
    description: "Become an expert in popular JavaScript frameworks like React, Angular, and Vue.",
    author: users[2].name,
    likes: 8,
    status: "public",
    date: '2023-05-19',
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    image_url: "",
    title: "Cybersecurity Best Practices",
    description: "Essential tips and practices to enhance your online security and protect against cyber threats.",
    author: users[3].name,
    likes: 11,
    status: "public",
    date: '2023-06-28',
  },
  {
    id: '13D07535-C59E-4157-A011-F8D2EF4E0CBB',
    image_url: "",
    title: "The Power of Data Visualization",
    description: "Unlock insights and communicate data effectively through visualizations.",
    author: users[4].name,
    likes: 4,
    status: "public",
    date: '2023-07-05',
  },
];

module.exports = { users, posts}